name: Kimono CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: install openssl
      run: sudo apt-get install -y openssl 
